# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
