# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freepost',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
