# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20170905_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='freepost',
            name='tmr_date',
            field=models.DateTimeField(default=0),
        ),
    ]
