# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_freepost_tmr_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freepost',
            name='tmr_date',
        ),
    ]
